"""Core contracts shared across geoseg modules."""

from geoseg.core.models import (
    BBoxXYWH,
    FigureClassification,
    PageOverview,
    PanelDetector,
    PanelInput,
    PipelineStep,
    QualityReview,
    QualityReviewer,
    RGBColor,
    RegionalAudit,
    Segmenter,
    SegmentationMeta,
    SegmentationResult,
    coerce_bbox_xywh,
    empty_segmentation_result,
    make_panel_input,
    make_whole_image_panel,
    validate_segmentation_result,
)

__all__ = [
    "BBoxXYWH",
    "FigureClassification",
    "PageOverview",
    "PanelDetector",
    "PanelInput",
    "PipelineStep",
    "QualityReview",
    "QualityReviewer",
    "RGBColor",
    "RegionalAudit",
    "Segmenter",
    "SegmentationMeta",
    "SegmentationResult",
    "coerce_bbox_xywh",
    "empty_segmentation_result",
    "make_panel_input",
    "make_whole_image_panel",
    "validate_segmentation_result",
]
